name: veda_components
description: description goes here
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.10.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

  veda_resources: any
  veda: any
  go_router: ^11.1.3
  permission_handler: ^11.0.1

  vector_graphics: ^1.1.7

  shimmer: ^3.0.0

  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
