// File generated by "melos run svg". Do not edit by hand.
// Copyright (c) 2023. The Avishek Subedi . All rights reserved.

final class Asset {
  static const AssetFooter footer = AssetFooter();
  static const AssetLookup lookup = AssetLookup();
  static const AssetIcons icons = AssetIcons();
  static const AssetHeader header = AssetHeader();
}

final class AssetFooter {
  const AssetFooter();

  String get search => 'assets/footer-bin/search.svg.vec';
  String get home => 'assets/footer-bin/home.svg.vec';
  String get add => 'assets/footer-bin/add.svg.vec';
  String get chat => 'assets/footer-bin/chat.svg.vec';
  String get profile => 'assets/footer-bin/profile.svg.vec';
}
final class AssetLookup {
  const AssetLookup();

  String get o => 'assets/lookup-bin/o.svg.vec';
  String get l => 'assets/lookup-bin/l.svg.vec';
  String get k => 'assets/lookup-bin/k.svg.vec';
  String get smile => 'assets/lookup-bin/smile.svg.vec';
  String get p => 'assets/lookup-bin/p.svg.vec';
  String get u => 'assets/lookup-bin/u.svg.vec';
}
final class AssetIcons {
  const AssetIcons();

  String get fb => 'assets/icons-bin/fb.svg.vec';
  String get x => 'assets/icons-bin/x.svg.vec';
  String get commentss => 'assets/icons-bin/commentss.svg.vec';
  String get camera => 'assets/icons-bin/camera.svg.vec';
  String get slogo => 'assets/icons-bin/slogo.svg.vec';
  String get google => 'assets/icons-bin/google.svg.vec';
  String get idea => 'assets/icons-bin/idea.svg.vec';
  String get share => 'assets/icons-bin/share.svg.vec';
  String get logo => 'assets/icons-bin/logo.svg.vec';
  String get menu => 'assets/icons-bin/menu.svg.vec';
  String get light => 'assets/icons-bin/light.svg.vec';
  String get heart => 'assets/icons-bin/heart.svg.vec';
}
final class AssetHeader {
  const AssetHeader();

  String get like => 'assets/header-bin/like.svg.vec';
  String get following => 'assets/header-bin/following.svg.vec';
  String get trending => 'assets/header-bin/trending.svg.vec';
  String get latest => 'assets/header-bin/latest.svg.vec';
}
